### ISSUE TITLE
Fragment Agenda not attached

### ISSUE THREAD

**Issue by benju69** [paug/AndroidMakersApp#16]

**Comment by n0tnull** [comment]
Here is the content of the logcat when it crashes :
`java.lang.IllegalStateException: Fragment AgendaFragment{abf169} not attached to Activity
                                                                                   at android.support.v4.app.Fragment.getResources(Fragment.java:608)
                                                                                   at android.support.v4.app.Fragment.getString(Fragment.java:632)
                                                                                   at fr.paug.androidmakers.ui.fragment.AgendaFragment.onAgendaLoaded(AgendaFragment.java:126)
                                                                                   at fr.paug.androidmakers.ui.fragment.AgendaFragment.access$300(AgendaFragment.java:41)
                                                                                   at fr.paug.androidmakers.ui.fragment.AgendaFragment$AgendaLoadListener.onAgendaLoaded(AgendaFragment.java:294)
                                                                                   at fr.paug.androidmakers.manager.AgendaRepository$1.onDataChange(AgendaRepository.java:51)
                                                                                   at com.google.android.gms.internal.zzegf.zza(Unknown Source)
                                                                                   at com.google.android.gms.internal.zzeia.zzbyc(Unknown Source)
                                                                                   at com.google.android.gms.internal.zzeig.run(Unknown Source)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by martinbonnin** [comment]
Closing due to inactivity. Please reopen if needed.
