### ISSUE TITLE
Reboot phone and SessionAlarmReceiver didn't appreciate

### ISSUE THREAD

**Issue by Joadar** [paug/AndroidMakersApp#27]
Hi,
I reboot my **Nexus 6P (8.1)** and a crash occurred (app version : 1.1.2) :
```
04-09 11:12:40.366 9459-9459/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: fr.paug.androidmakers, PID: 9459
                                                 java.lang.RuntimeException: Unable to start receiver fr.paug.androidmakers.receiver.SessionAlarmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=SCHEDULE_ALL_STARRED_BLOCKS cmp=fr.paug.androidmakers/.service.SessionAlarmService }: app is in background uid UidRecord{7dee732 u0a597 RCVR idle change:uncached procs:1 seq(0,0,0)}
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
                                                     at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                  Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=SCHEDULE_ALL_STARRED_BLOCKS cmp=fr.paug.androidmakers/.service.SessionAlarmService }: app is in background uid UidRecord{7dee732 u0a597 RCVR idle change:uncached procs:1 seq(0,0,0)}
                                                     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
                                                     at android.app.ContextImpl.startService(ContextImpl.java:1477)
                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:650)
                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:650)
                                                     at fr.paug.androidmakers.receiver.SessionAlarmReceiver.onReceive(Unknown Source:10)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
                                                     at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by benju69** [comment]
https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

**Comment by benju69** [comment]
Should be fixed now
