### ISSUE TITLE
Invalid channel for service notification

### ISSUE THREAD

**Issue by mdupierreux** [paug/AndroidMakersApp#28]
After the last update, the app keeps crashing with this error : 

2018-04-11 08:35:50.092 12636-12636/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.paug.androidmakers, PID: 12636
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2018-04-11 08:35:50.092 12636-12636/? E/UncaughtException: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by mdupierreux** [comment]
Looks like you have to create your own notification channels with 8.1 : https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1

**Comment by benju69** [comment]
Yes my fault, there is an empty notification somewhere, all others notifications have a channel, should be fixed in next version

**Comment by mdupierreux** [comment]
In SessionAlarmService.java I think 

NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this)
                .setContentTitle(notifTitle)
                .setContentText(notifContent)
                .setColor(getResources().getColor(R.color.colorPrimary))
                .setDefaults(Notification.DEFAULT_SOUND | Notification.DEFAULT_VIBRATE)
                .setLights(
                        SessionAlarmService.NOTIFICATION_ARGB_COLOR,
                        SessionAlarmService.NOTIFICATION_LED_ON_MS,
                        SessionAlarmService.NOTIFICATION_LED_OFF_MS)
                .setSmallIcon(R.drawable.ic_event_note_white_24dp)
                .setContentIntent(resultPendingIntent)
                .setPriority(Notification.PRIORITY_MAX)
                .setAutoCancel(true);

**Comment by benju69** [comment]
Yep I have fixed this notification, Look in the 2018 branch

**Comment by mdupierreux** [comment]
Any ETA for the new version ? (since I can't use the app atm 😉 )

**Comment by benju69** [comment]
Just pushed a new version, let me know if you have problems
